#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $SURTURBOT_REPO == "Thanosbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L01lb3dVc2VyYm90L2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $SURTURBOT_REPO == "Thanosbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L01lb3dVc2VyYm90L2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    elif [[ $SURTURBOT_REPO =~ $regex ]]
    then
        if [[ $SURTURBOT_REPO_BRANCH ]]
        then
            echo "${MEOW_REPO}/archive/${MEOW_REPO_BRANCH}.zip"
        else
            echo "${SURTURBOT_REPO}/archive/Thanosbot.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2thYWwwNDA4L01lb3dVc2VyYm90L2FyY2hpdmUvbWFpbi56aXA=" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="Thanos-UserBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    SURTURBOTPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $SURTURBOTPATH
    echo "  • Starting Thanosbot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Thanosbot
}

start_bot
